# Generated by Django 3.0.6 on 2020-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simmuser', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('dateplanned', models.DateTimeField(verbose_name='date prevue')),
                ('dcu', models.BooleanField(default=False)),
                ('gds', models.BooleanField(default=False)),
                ('appext', models.BooleanField(default=False)),
                ('printers', models.BooleanField(default=False)),
                ('gdp', models.BooleanField(default=False)),
                ('backup', models.BooleanField(default=False)),
                ('invoice', models.BooleanField(default=False)),
                ('apex', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('byteam', models.CharField(choices=[('CE', 'SIMM-Centre'), ('ME', 'SIMM-Mercier'), ('MO', 'SIMM-MO')], max_length=20)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reinstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simmuser', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('dateplanned', models.DateTimeField(verbose_name='date prevue')),
                ('dcu', models.BooleanField(default=False)),
                ('datatransfert', models.BooleanField(default=False)),
                ('appext', models.BooleanField(default=False)),
                ('printers', models.BooleanField(default=False)),
                ('backup', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('byteam', models.CharField(choices=[('CE', 'SIMM-Centre'), ('ME', 'SIMM-Mercier'), ('MO', 'SIMM-MO')], max_length=20)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simmuser', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('dateplanned', models.DateTimeField(verbose_name='date prevue')),
                ('dcu', models.BooleanField(default=False)),
                ('gds', models.BooleanField(default=False)),
                ('datatransfert', models.BooleanField(default=False)),
                ('appext', models.BooleanField(default=False)),
                ('printers', models.BooleanField(default=False)),
                ('gdp', models.BooleanField(default=False)),
                ('backupnew', models.BooleanField(default=False)),
                ('backupold', models.BooleanField(default=False)),
                ('invoice', models.BooleanField(default=False)),
                ('apex', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('byteam', models.CharField(choices=[('CE', 'SIMM-Centre'), ('ME', 'SIMM-Mercier'), ('MO', 'SIMM-MO')], max_length=20)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simmuser', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('computer', models.CharField(max_length=200)),
                ('dateplanned', models.DateTimeField(verbose_name='date prevue')),
                ('dcu', models.BooleanField(default=False)),
                ('appext', models.BooleanField(default=False)),
                ('adminblank', models.BooleanField(default=False)),
                ('lduninstall', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=200)),
                ('byteam', models.CharField(choices=[('CE', 'SIMM-Centre'), ('ME', 'SIMM-Mercier'), ('MO', 'SIMM-MO')], max_length=20)),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('roles', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=200)),
            ],
        ),
    ]
