# Generated by Django 3.0.6 on 2020-05-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='install',
            name='type',
            field=models.CharField(choices=[('Ins', 'Installation'), ('Reins', 'Réinstallation'), ('Rep', 'Remplacement'), ('Stud', 'Pc étudiant')], max_length=200),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='type',
            field=models.CharField(choices=[('Ins', 'Installation'), ('Reins', 'Réinstallation'), ('Rep', 'Remplacement'), ('Stud', 'Pc étudiant')], max_length=200),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='type',
            field=models.CharField(choices=[('Ins', 'Installation'), ('Reins', 'Réinstallation'), ('Rep', 'Remplacement'), ('Stud', 'Pc étudiant')], max_length=200),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='type',
            field=models.CharField(choices=[('Ins', 'Installation'), ('Reins', 'Réinstallation'), ('Rep', 'Remplacement'), ('Stud', 'Pc étudiant')], max_length=200),
        ),
    ]
