# Generated by Django 3.0.6 on 2020-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0002_auto_20200530_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='dateplanned',
            field=models.DateField(verbose_name='date prevue'),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='dateplanned',
            field=models.DateField(verbose_name='date prevue'),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='dateplanned',
            field=models.DateField(verbose_name='date prevue'),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='dateplanned',
            field=models.DateField(verbose_name='date prevue'),
        ),
    ]
