# Generated by Django 3.0.6 on 2020-06-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0003_auto_20200531_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
