# Generated by Django 3.0.6 on 2020-06-05 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0004_auto_20200605_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='install',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-\\]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-\\]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-\\]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='comments',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\-\\]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
    ]
