# Generated by Django 3.0.6 on 2020-06-05 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0005_auto_20200605_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='person',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Chiffres et caracteres speciaux interdits')]),
        ),
    ]
