# Generated by Django 3.0.7 on 2020-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0006_auto_20200605_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='install',
            name='person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reinstall',
            name='person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='person',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentpc',
            name='person',
            field=models.CharField(max_length=200),
        ),
    ]
