# Generated by Django 3.0.6 on 2020-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDR', '0007_auto_20200610_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='install',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reinstall',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replacement',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpc',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
